version: "3"

services:
  www:
    image: ghcr.io/soruly/trace.moe-www:latest
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
    ports:
      - ${WWW_PORT}:3000
    networks:
      trace_moe_net:

  api:
    image: ghcr.io/soruly/trace.moe-api:latest
    depends_on:
      - mariadb
      - liresolr
    restart: unless-stopped
    environment:
      - VIDEO_PATH=/mnt/c/trace.moe/video/
      - HASH_PATH=/mnt/c/trace.moe/hash/
      - TRACE_API_SALT=${TRACE_API_SALT}
      - TRACE_ALGO=cl
      - TRACE_ACCURACY=${TRACE_ACCURACY}
      - MAX_WORKER=${MAX_WORKER}
      - MEDIA_QUEUE=${MEDIA_QUEUE}
      - SEARCH_QUEUE=${SEARCH_QUEUE}
      - USE_IMAGE_PROXY=${USE_IMAGE_PROXY}
      - SOLA_DB_HOST=mariadb
      - SOLA_DB_PORT=3306
      - SOLA_DB_USER=root
      - SOLA_DB_PWD=${MARIADB_ROOT_PASSWORD}
      - SOLA_DB_NAME=sola
      - SOLA_SOLR_LIST=http://172.17.0.1:${SOLR_PORT}/solr/
      - SOLA_SOLR_SIZE=1
      - SERVER_PORT=3000
    ports:
      - ${API_PORT}:3000
    volumes:
      - type: bind
        source: ${VIDEO_PATH}
        target: /mnt/c/trace.moe/video/
      - type: bind
        source: ${HASH_PATH}
        target: /mnt/c/trace.moe/hash/
    networks:
      trace_moe_net:

  adminer:
    image: adminer:latest
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_USER=root
      - ADMINER_DEFAULT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      trace_moe_net:

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ${MYSQL_DIR}
        target: /var/lib/mysql
    networks:
      trace_moe_net:

  liresolr:
    image: ghcr.io/soruly/liresolr:latest
    command: solr-precreate cl_0 /opt/solr/server/solr/configsets/liresolr
    restart: unless-stopped
    environment:
      - SOLR_HEAP=${SOLR_HEAP}
    ports:
      - ${SOLR_PORT}:8983
    volumes:
      - type: bind
        source: ${SOLR_DIR}
        target: /var/solr
    networks:
      trace_moe_net:

networks:
  trace_moe_net:
    driver: bridge
